import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  head,body,
}: Readonly<{
  head: React.ReactNode;
  body: React.ReactNode;
}>) {
  return (
    <html data-bs-theme="light" lang="en">
      <head>{head}</head>
      <body className={inter.className} style={{ background: "var(--bs-body-bg)" }}>{body}</body>
      <script async src="assets/bootstrap/js/bootstrap.min.js"></script>
    </html>
  );
}
